/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package zoo.project;

import java.awt.event.WindowListener;
import javax.swing.ImageIcon;

/**
 *
 * @author SALLEN5597
 */
public class MainZoo extends javax.swing.JFrame {

    @Override
    public synchronized void addWindowListener(WindowListener l) {
        super.addWindowListener(l); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    
    
    /**
     * Creates new form MainZoo
     */
    public MainZoo() {
        initComponents();
        
        ImageIcon mainzoo = new ImageIcon("4826e8dd44949ce7b0b5b5dea2a995ea");
        
        the_pnl.remove(superpanel);
        the_pnl.remove(fingerterian_pnl);
        the_pnl.remove(cubrin_pnl);
        the_pnl.remove(fire_pnl);
        the_pnl.remove(water_pnl);
        the_pnl.remove(lich_pnl);
        the_pnl.remove(noit_pnl);
        the_pnl.remove(gelo_pnl);
        the_pnl.remove(meyorpin_pnl);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        the_pnl = new javax.swing.JTabbedPane();
        mainpanel = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        superpanel = new javax.swing.JPanel();
        fire_wyvern = new javax.swing.JToggleButton();
        water_wyvern = new javax.swing.JToggleButton();
        lich_wyvern = new javax.swing.JToggleButton();
        fingerterian_pnl = new javax.swing.JPanel();
        noit_btn = new javax.swing.JToggleButton();
        gelo_btn = new javax.swing.JToggleButton();
        meyorpin_btn = new javax.swing.JToggleButton();
        cubrin_pnl = new javax.swing.JTabbedPane();
        fire_pnl = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        water_pnl = new javax.swing.JPanel();
        lich_pnl = new javax.swing.JPanel();
        noit_pnl = new javax.swing.JPanel();
        gelo_pnl = new javax.swing.JPanel();
        meyorpin_pnl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton4 = new javax.swing.JToggleButton();
        gondor_pnl = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        the_pnl.setBackground(new java.awt.Color(255, 255, 255));

        mainpanel.setBackground(new java.awt.Color(204, 204, 255));

        jToggleButton1.setText("Wyvern");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Fingerterian");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("Cubrin");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(jToggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(608, Short.MAX_VALUE))
        );

        the_pnl.addTab("tab1", mainpanel);

        fire_wyvern.setText("fire");
        fire_wyvern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fire_wyvernActionPerformed(evt);
            }
        });

        water_wyvern.setText("water");
        water_wyvern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                water_wyvernActionPerformed(evt);
            }
        });

        lich_wyvern.setText("lich");
        lich_wyvern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lich_wyvernActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout superpanelLayout = new javax.swing.GroupLayout(superpanel);
        superpanel.setLayout(superpanelLayout);
        superpanelLayout.setHorizontalGroup(
            superpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(superpanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(fire_wyvern)
                .addGap(122, 122, 122)
                .addComponent(water_wyvern)
                .addGap(177, 177, 177)
                .addComponent(lich_wyvern)
                .addContainerGap(1585, Short.MAX_VALUE))
        );
        superpanelLayout.setVerticalGroup(
            superpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(superpanelLayout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addGroup(superpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fire_wyvern)
                    .addComponent(water_wyvern)
                    .addComponent(lich_wyvern))
                .addContainerGap(879, Short.MAX_VALUE))
        );

        the_pnl.addTab("Wyvern", superpanel);

        noit_btn.setText("Noit");
        noit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noit_btnActionPerformed(evt);
            }
        });

        gelo_btn.setText("Gelo");
        gelo_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gelo_btnActionPerformed(evt);
            }
        });

        meyorpin_btn.setText("Meyorpin");
        meyorpin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meyorpin_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fingerterian_pnlLayout = new javax.swing.GroupLayout(fingerterian_pnl);
        fingerterian_pnl.setLayout(fingerterian_pnlLayout);
        fingerterian_pnlLayout.setHorizontalGroup(
            fingerterian_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fingerterian_pnlLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(noit_btn)
                .addGap(89, 89, 89)
                .addComponent(gelo_btn)
                .addGap(129, 129, 129)
                .addComponent(meyorpin_btn)
                .addContainerGap(1663, Short.MAX_VALUE))
        );
        fingerterian_pnlLayout.setVerticalGroup(
            fingerterian_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fingerterian_pnlLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addGroup(fingerterian_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noit_btn)
                    .addComponent(gelo_btn)
                    .addComponent(meyorpin_btn))
                .addContainerGap(1019, Short.MAX_VALUE))
        );

        the_pnl.addTab("Fingerterian", fingerterian_pnl);
        the_pnl.addTab("Cubrin", cubrin_pnl);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/project/zozozozo.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(112, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(68, 68, 68))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout fire_pnlLayout = new javax.swing.GroupLayout(fire_pnl);
        fire_pnl.setLayout(fire_pnlLayout);
        fire_pnlLayout.setHorizontalGroup(
            fire_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fire_pnlLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1210, Short.MAX_VALUE))
        );
        fire_pnlLayout.setVerticalGroup(
            fire_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fire_pnlLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(603, Short.MAX_VALUE))
        );

        the_pnl.addTab("Fire", fire_pnl);

        javax.swing.GroupLayout water_pnlLayout = new javax.swing.GroupLayout(water_pnl);
        water_pnl.setLayout(water_pnlLayout);
        water_pnlLayout.setHorizontalGroup(
            water_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2115, Short.MAX_VALUE)
        );
        water_pnlLayout.setVerticalGroup(
            water_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
        );

        the_pnl.addTab("Water", water_pnl);

        javax.swing.GroupLayout lich_pnlLayout = new javax.swing.GroupLayout(lich_pnl);
        lich_pnl.setLayout(lich_pnlLayout);
        lich_pnlLayout.setHorizontalGroup(
            lich_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2115, Short.MAX_VALUE)
        );
        lich_pnlLayout.setVerticalGroup(
            lich_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
        );

        the_pnl.addTab("Lich", lich_pnl);

        javax.swing.GroupLayout noit_pnlLayout = new javax.swing.GroupLayout(noit_pnl);
        noit_pnl.setLayout(noit_pnlLayout);
        noit_pnlLayout.setHorizontalGroup(
            noit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2115, Short.MAX_VALUE)
        );
        noit_pnlLayout.setVerticalGroup(
            noit_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
        );

        the_pnl.addTab("Noit", noit_pnl);

        javax.swing.GroupLayout gelo_pnlLayout = new javax.swing.GroupLayout(gelo_pnl);
        gelo_pnl.setLayout(gelo_pnlLayout);
        gelo_pnlLayout.setHorizontalGroup(
            gelo_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2115, Short.MAX_VALUE)
        );
        gelo_pnlLayout.setVerticalGroup(
            gelo_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
        );

        the_pnl.addTab("Gelo", gelo_pnl);

        meyorpin_pnl.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/zoo/project/4826e8dd44949ce7b0b5b5dea2a995ea.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        meyorpin_pnl.add(jLabel2);
        jLabel2.setBounds(120, 330, 670, 440);

        jToggleButton4.setText("jToggleButton4");
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        meyorpin_pnl.add(jToggleButton4);
        jToggleButton4.setBounds(440, 510, 105, 25);

        the_pnl.addTab("Meyorpin", meyorpin_pnl);

        javax.swing.GroupLayout gondor_pnlLayout = new javax.swing.GroupLayout(gondor_pnl);
        gondor_pnl.setLayout(gondor_pnlLayout);
        gondor_pnlLayout.setHorizontalGroup(
            gondor_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2115, Short.MAX_VALUE)
        );
        gondor_pnlLayout.setVerticalGroup(
            gondor_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
        );

        the_pnl.addTab("Gondor", gondor_pnl);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2115, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1270, Short.MAX_VALUE)
        );

        the_pnl.addTab("Dralopian", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(the_pnl)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(the_pnl, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        the_pnl.addTab("Fingerterian", fingerterian_pnl);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        the_pnl.addTab("Cubrin", cubrin_pnl);
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void fire_wyvernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fire_wyvernActionPerformed
        the_pnl.addTab("Fire", fire_pnl);
    }//GEN-LAST:event_fire_wyvernActionPerformed

    private void water_wyvernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_water_wyvernActionPerformed
        the_pnl.addTab("Water", water_pnl);
    }//GEN-LAST:event_water_wyvernActionPerformed

    private void lich_wyvernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lich_wyvernActionPerformed
        the_pnl.addTab("Lich", lich_pnl);
    }//GEN-LAST:event_lich_wyvernActionPerformed

    private void noit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noit_btnActionPerformed
       the_pnl.addTab("Noit", noit_pnl);
    }//GEN-LAST:event_noit_btnActionPerformed

    private void gelo_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gelo_btnActionPerformed
        the_pnl.addTab("Gelo", gelo_pnl);
    }//GEN-LAST:event_gelo_btnActionPerformed

    private void meyorpin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meyorpin_btnActionPerformed
        the_pnl.addTab("Meyorpin", meyorpin_pnl);
    }//GEN-LAST:event_meyorpin_btnActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed

        the_pnl.addTab("Wyvern", superpanel);

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        the_pnl.remove(meyorpin_pnl);
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainZoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainZoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainZoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainZoo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainZoo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane cubrin_pnl;
    private javax.swing.JPanel fingerterian_pnl;
    private javax.swing.JPanel fire_pnl;
    private javax.swing.JToggleButton fire_wyvern;
    private javax.swing.JToggleButton gelo_btn;
    private javax.swing.JPanel gelo_pnl;
    private javax.swing.JPanel gondor_pnl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JPanel lich_pnl;
    private javax.swing.JToggleButton lich_wyvern;
    private javax.swing.JPanel mainpanel;
    private javax.swing.JToggleButton meyorpin_btn;
    private javax.swing.JPanel meyorpin_pnl;
    private javax.swing.JToggleButton noit_btn;
    private javax.swing.JPanel noit_pnl;
    private javax.swing.JPanel superpanel;
    private javax.swing.JTabbedPane the_pnl;
    private javax.swing.JPanel water_pnl;
    private javax.swing.JToggleButton water_wyvern;
    // End of variables declaration//GEN-END:variables
}
